### ISSUE TITLE
Potential bug in wrlong disassembly

### ISSUE THREAD

**Issue by redvers** [davehein/p2gcc#1]
tl;dr, some of the values for wrlong et al have hard-coded constants for s which map to assembly keywords - looks like this one fell through your filter:

```
0xfc6005e1
Maps to:
iex(62)> P2Testing.Disasm.d(<<0xfc6005e1::size(32)>>)
"1111 1100011 000 000000010 111100001"
```

So, instruction:
```
EEEE 1100011 0LI DDDDDDDDD SSSSSSSSS        WRLONG  D/#,S/#/PTRx
1111 1100011 000 000000010 111100001
```

So, it's a WRLONG 2, *something.

Looking at the docs:
```
#%0AAAAAAAA                    - No AUGS, 8-bit immediate address
#%1SUPNNNNN                    - No AUGS, PTRx expression with 5-bit scaled index
```

(there is no AUGS)

So, it should match:
```
#%1SUPNNNNN                    - No AUGS, PTRx expression with 5-bit scaled index
  111100001

more specifically:
111100001     PTRB++
```

So I end up with wrlong 2, ptrb++

p2dump isn't catching that constant so is mapping it to $1e1 instead (which I assume would end up producing the same bytecode instruction).

p2dump produces: wrlong  2, $1e1

**Comment by redvers** [comment]
nb, it is implemented for rdword eg:
```
0dc0 fae781e1              rdword  $1c0, ptrb++
```

**Comment by davehein** [comment]
wrlong 2, $1e1 is correct since the immediate bit isn't set.
